### ISSUE TITLE
Is `hiopVectorPar::startingAtCopyFromStartingAt` correctly implemented?

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#56] opened 2020-07-11 02:45 UTC
It seems that local variable `howManyToCopy` and `howManyToCopyDest` are flipped around in function `hiopVectorPar::startingAtCopyFromStartingAt`. 
- `howManyToCopy` is the number of elements at the destination that will be overwritten.
- `howManyToCopyDest` is number of source element that will be written to the destination. 
The assertion in this function will enforce:
```c++
  assert(howManyToCopy <= howManyToCopyDest);
```
what is, I think, opposite of what is intended (despite names of these variables suggesting otherwise).

Also, it seems the function arguments seem to have misleading meaning since `start_idx_src` is destination and `start_idx_dest` is source offset.

This (possible) bug does not affect the code, because [only time this function is called](https://github.com/LLNL/hiop/blob/master/src/Optimization/hiopKKTLinSysMDS.cpp#L167) the source and destination are of the same size and both offsets are zero.

@cnpetra

**Comment by cnpetra** [comment] 2020-07-14 00:49
the method seems to be working fine, but the naming of the variables is very confusing

it think should be / was intended to be
```
void hiopVectorPar::startingAtCopyFromStartingAt(int start_idx_dest, const hiopVector& v_src, int start_idx_src)
```

**Comment by cnpetra** [comment] 2020-07-14 00:52
also documentation in the header confuses 'src' with 'dest' ` copy from 'dest' starting at 'start_idx_dest' to 'this' starting at 'start_idx_src'  `

**Comment by pelesh** [comment] 2020-07-14 03:37
If this is the case, it seems to me the assertion `assert(howManyToCopy <= howManyToCopyDest);` is also flipped around, since `src` and `dest` have opposite meaning: 
```c++
  int howManyToCopy = this->n_local - start_idx_src;
  const int howManyToCopyDest = v.n_local-start_idx_dest;
  assert(howManyToCopy <= howManyToCopyDest);
```
This will work only if `howManyToCopy == howManyToCopyDest`. To make it work as (I think is) intended, you need something like this:
```c++
  int howManyToCopyDest = this->n_local - start_idx_dest;
  const int howManyToCopySrc = v.n_local - start_idx_src;

  // Make sure there is enough space in dest to copy
  assert(howManyToCopySrc <= howManyToCopyDest);

  // Copy all you got in src from start_idx_src to the end of the vector
  memcpy(data_ + start_idx_dest, v.data_ + start_idx_src, howManyToCopySrc*sizeof(double));    
``` 
Did I untangle this correctly?

**Comment by cnpetra** [comment] 2020-07-20 21:07
yes, I put it in PR #60

**Comment by cnpetra** [comment] 2020-07-20 21:08
moving the discussion to PR #60 and closing this.

**Closed by cnpetra** 2020-07-20 21:08 UTC
