### ISSUE TITLE
conflicts in CUDA libraries and pthread issue

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#111] opened 2020-11-18 21:21 UTC
Build with option -DCMAKE_BUILD_TYPE=DEBUG -DHIOP_USE_GPU=ON, and keep others as default.
Successful to compile hiop EX1-EX7 with magma and coninhsl, but fail to compile the unit tests.
Also cmake gives some warnings about possible conflicts in the run-time libararies.
The log file from cmake/make are provided below:
[make_log.txt](https://github.com/LLNL/hiop/files/5562750/make_log.txt)
[cmake_log.txt](https://github.com/LLNL/hiop/files/5562751/cmake_log.txt)

**Comment by pelesh** [comment] 2020-11-18 21:26
@nychiang, could you provide a reproducible description of the problem?

**Comment by nychiang** [comment] 2020-11-18 21:46
I use branch [dev-fix#79](https://github.com/LLNL/hiop/tree/dev-fix%2379), which is rebased on to `ci-cmake-fix#107`, cotaining the latest code from `develop`.
The test platform is Lassen, and following modules are loaded:
 ` cuda/10.1.243,  gcc/8.3.1, spectrum-mpi/rolling-release, magma/2.5.3, essl/6.2.1, cmake/3.14.5`
To compile the code, I use the following command in a subfolder `build`
`cmake -DCMAKE_BUILD_TYPE=DEBUG -DHIOP_USE_GPU=ON ..`

It ends up compiling the examples successfully, but fails to compile the objects for unit test.
The error is platform dependent, according one issue reported to cmake gitlab https://gitlab.kitware.com/cmake/cmake/-/issues/18008

**Comment by pelesh** [comment] 2020-11-24 00:13
@nychiang, I am not quite sure what is going on here, but according to your log files it seems that the issue is due to linking being done with `nvcc` instead of `gcc`. I was not able to reproduce this.

**Comment by nychiang** [comment] 2020-11-24 03:45
This only happens on Lassen (LLNL). The error is platform dependent (see the link I attached in the previous reply), I couldn't reproduce it on summit neither. 
Maybe we should move forward and leave this ticket open.

**Comment by cnpetra** [comment] 2021-02-02 16:52
closing this since since the fix is on the user's end.

**Closed by cnpetra** 2021-02-02 16:52 UTC
Labels: bug
