### ISSUE TITLE
Flawed logic in cmake for combinations of GPU, RAJA, UMPIRE, and MAGMA flags

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#121] opened 2020-11-23 22:55 UTC
Tried to use different options to compile the code and noticed some error when combining GPU, RAGA, UMPIRE and MAGMA.
For example:
1.  Switch off GPU and RAJA --- fail
    `cmake -DHIOP_USE_GPU=OFF -DHIOP_USE_RAJA=OFF -DHIOP_SPARSE=OFF ..`
error message:
/ccs/home/chiang7/project/hiop/src/LinAlg/hiopVectorRajaPar.cpp:73:10: fatal error: RAJA/RAJA.hpp: No such file or directory
   73 | #include <RAJA/RAJA.hpp>

2.	Switch off GPU --- fail 
    `cmake -DHIOP_SPARSE=OFF -DHIOP_USE_GPU=OFF ..`
cmake configuration error:
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION

If we ignore this error and continue to build hiop, then I will get errors showing MAGMA is not referenced.

Therefore, if I want to switch off MAGMA, I need to switch off RAJA, UMPIRE and GPU:
That is, using command "cmake -DHIOP_USE_GPU=OFF -DHIOP_USE_RAJA=OFF -DHIOP_USE_UMPIRE=OFF -DHIOP_SPARSE=OFF -DHIOP_USE_MAGMA=OFF .."

**Comment by nychiang** [comment] 2020-11-23 23:08
You can also reproduce the similar error in branch `develop`.

**Comment by pelesh** [comment] 2020-11-23 23:49
@nychiang thank you for reporting this! I think these should not be difficult to fix. Do you want to first complete #120 merge before we tackle this?

CC @cnpetra @ashermancinelli

**Comment by ashermancinelli** [comment] 2020-11-23 23:55
> @nychiang thank you for reporting this! I think these should not be difficult to fix. Do you want to first complete #120 merge before we tackle this?
> 
> CC @cnpetra @ashermancinelli

Must this be addressed for #120 to pass CI? If so, I don't mind spending some time to get this working before merging.

**Comment by pelesh** [comment] 2020-11-24 01:07
@ashermancinelli, I suggest we keep fix for this issue separate from #120. These errors occur only when RAJA is on, but GPU support is off. I think CMake will need another overhaul beyond fix for this issue. @cnpetra, what do you think?

**Comment by cnpetra** [comment] 2020-11-24 01:51
yes, after #120 is merged. Does not interfere with CI as CI does not test this corner case.

**Comment by cnpetra** [comment] 2020-11-24 21:54
I think this was fixed by #124    @nychiang please confirm

**Comment by pelesh** [comment] 2020-11-24 21:58
> I think this was fixed by #124 @nychiang please confirm

I think #124 fixes only part of the issues. After `sparse-develop` is merged, it would be good to refactor CMake to account for multiple hardware backends and multiple linear solvers interfaces. I would leave this issue as the reminder.

**Comment by pelesh** [comment] 2020-11-25 21:00
I propose following solution for the rest of the issues mentioned here:
1. RAJA and Umpire should be enabled simultaneously in CMake using a single flag. I suggest to use `HIOP_USE_RAJA` flag as RAJA has better name recognition than Umpire. For now, I don't see a legitimate use case in HiOp where we would want to use one without the other.
2. Refactor logic when setting `HIOP_USE_GPU`:
    - Once set to `On` user should be presented choice of selecting _either_ CUDA _or_ HIP. We should eventually support the mixture of the two, but that would require more changes to the code. For now, this should suffice.
        - If CUDA is selected `HIOP_USE_MAGMA` is set to `On`. 
            - This should stay like this until there is a configuration option to disable building dense and MDS solvers.
            - If `HIOP_SPARSE` is `On`, then `HIOP_USE_STRUMPACK` is set to `On`, as well.
            - If neither Magma nor Strumpack are found, CMake should send back message that CUDA support is not enabled and turn it off.
        - If HIP is selected `HIOP_USE_HIPMAGMA` is set to `On`. Implement similar logic as for CUDA.
        - If neither CUDA nor HIP support are available, the CMake should return message to that end and turn `HIOP_USE_GPU` off.
     - If GPU support is off, then no options for choosing CUDA or HIP should be visible to the user.
3. It is user's responsibility to provide RAJA and Umpire dependencies with support for user's hardware.
    - My understanding is if RAJA is built with CUDA and OpenMP backends, the user can still choose to run e.g. only OpenMP backend in HiOp and will not need to link to CUDA libraries.
    - To get the same with Umpire, my understanding is Umpire needs to be built as three libs `umpire_common`, `umpire_cuda` and `umpire_openmp`. I am not sure how easy or difficult this is.

Feedback and discussion on this solution is welcome.

CC @davidbeckingsale for clarifications on Umpire and RAJA.

**Comment by davidbeckingsale** [comment] 2020-11-25 21:35
Umpire will need to be built with whatever GPU backend you want, e.g. a CUDA build, a HIP build, and an OpenMP target build. You do not need a different build for CPU OpenMP since we don't do anything special for that. You do need a special CPU-only Umpire build, since the builds with a GPU backend included will check for devices on startup.

I would recommend using this same approach for RAJA too right now, since HIP and OpenMP currently cannot be compiled together.

**Comment by ashermancinelli** [comment] 2020-12-02 22:48
@pelesh mentioned offline that a note in the readme about supported compilers should be added in line with this issue - what compilers do we currently support? I've only ever used gcc >=7.3 and clang 10.

**Comment by cnpetra** [comment] 2020-12-07 19:30
I do not have lower bound on gcc version, the lower the better. I say we should use the lowest that enables all RAJA features we need.

**Comment by pelesh** [comment] 2020-12-12 02:09
@nychiang, I cannot reproduce anymore errors 1. and 2. as reported in this issue. In particular, I believe 1. has been fixed in #153.

The only outstanding item here is that you still cannot switch off Magma without turning off GPU support at the same time. This was by design, because for a while Magma was only GPU-enabled linear solver we could use. Perhaps we should close this issue and open another one with remaining items?

**Comment by nychiang** [comment] 2020-12-12 04:55
sure, I think 1 has been fixed. 
2 will be covered in step 2 in your proposed solution.

**Comment by pelesh** [comment] 2020-12-16 23:02
The bug part of this issue has been fixed. The rest of the discussed is tracked in #160. Closing this issue.

**Closed by pelesh** 2020-12-16 23:02 UTC
Labels: bug
