### ISSUE TITLE
Hessian evaluation called before Hessian matrix is alocated

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#358] opened 2021-11-06 00:09 UTC
It seems that HiOp Sparse module will call Hessian matrix evaluation at least once before the matrix is allocated. Because of that, responsibility is passed to model developers (HiOp users) to check if the Hessian is allocated. For example, in [Hessian evaluation](https://github.com/LLNL/hiop/blob/develop/src/Drivers/nlpSparse_ex6.cpp#L187) in example `nlpSparse_ex6.cpp`, user needs to provide if-guards like this:
```c++
  if(iHSS!=NULL && jHSS!=NULL) {
    for(int i=0; i<n; i++)
      iHSS[i] = jHSS[i] = i;
  }
```
Consider checking within optimization algorithm whether Hessian matrix is allocated before calling Hessian evaluation function. This will give user cleaner way to interact with HiOp.

It seems the same issue is with constraint Jacobians.

Note this issue was observed in #356, but misidentified.

**Comment by nychiang** [comment] 2021-11-06 01:40
@pelesh @shakedregev @cnpetra 

I tried to check this issue and I can reproduce the error as Shaked did.
In short, HiOp Sparse does NOT call Hessian matrix evaluation before the matrix is allocated.

Since the sparsity of Hes only need to be filled once, in the first call of hessian evaluation, the `iHSS` and `jHSS` arguments are not `nullptr`. After this call, the sparsity is fixed and hence we only need to update the matrix value from the callback function. That is, now the arguments of `iHSS` and `jHSS`  will be `nullptr` and `MHSS` is not NULL.

Using Shaked's previous commits as an example, the code receives segfault when assigning sparsity 
```
    iHSS[0] = jHSS[0] = 0;
    iHSS[1] = 0;
    jHSS[1] = 1;
```
in the 2nd call of hessian evaluation, when the sparsity is fixed and solver only expects user updating the values. 
See [here](https://github.com/LLNL/hiop/blob/ae3318a74e2d9737210cae81cf0a0450e03dab4f/src/Optimization/hiopNlpFormulation.cpp#L1687-L1690), which shows that HiOp passes `nullptr` as the argument for `iHSS` and `jHSS`. Unfortunately, user needs to identify this to avoid segfault.

Not sure if we need to fix this, since we use the same idea from Ipopt, see its documentation from [here](https://coin-or.github.io/Ipopt/classIpopt_1_1TNLP.html#a26b9145267e2574c53acc284fef1c354).
I would rather keeping the current design due to the same reason.

Same observation applies to constraint Jacobians.

**Comment by nychiang** [comment] 2021-12-11 00:36
@cnpetra I think we can close this issue.

**Closed** 2021-12-28 18:29 UTC
